[package]
name = "performance_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
compact_str = { version = "0.9.0", default-features = false}
fxhash = { version = "0.2.1", default-features = false}
unix-print = "0.1.0"
